services:
  transformers-notebook:
    # image: jupyter/tensorflow-notebook:latest
    build: ./
    ports:
      - 8000:8888
    environment:
      - JUPYTER_TOKEN=iamironman
    volumes:
      - ./:/home/jovyan/